### ISSUE TITLE
Warning: Error in {: task 1 failed - "there is no package called 'XML'"   [No stack trace available]

### ISSUE THREAD

**Issue by miaohaofei** [mathiaskalxdorf/IceR#14]
Hi
   when  I Installed the IceR and RUN it, it has the error"Warning: Error in {: task 1 failed - "there is no package called 'XML'"
  [No stack trace available]",but  I also install the XML package.what is the problem? thank you very much!

**Comment by mathiaskalxdorf** [comment]
Hey,

can you give more details please? What is your OS, which R version are you using, which IceR version are you using (master or development branch)? Can you please also report the whole console output so that I can see at which step exactly the error occurs?

Thanks.

Mathias
