### ISSUE TITLE
FAIMS Data, Frag Pipe and integration

### ISSUE THREAD

**Issue by Peer2011** [mathiaskalxdorf/IceR#15]
Dear Matthias, 

We have generated the input files you propose for the ICER workflow from Frag Pipe output data via some R scripts. How about FAIMS Data? Is it possible to calculate those as well with ICER? We have 2 replicates with negative and positive FAIMS settings for each biological replicate. Are all calculations done on the peptide level and if yes how do we integrate this for the protein level? Would we need 410 entries in the preprocess_quant.txt or 205 (as the number of biological replicates) with already integrated intensity.

Best, Peer

**Comment by mathiaskalxdorf** [comment]
Hi Peer,

we did not test IceR for FAIMS data so I can not really give advice on that. You will have to play around with it and see how it works. Consider reading the closed issue "Questions about FAIMS data and Proteome Discoverer output #7". Here was a similar question and maybe the conversation helps to get an idea how IceR could be used for FAIMS data. At least at the moment there is no simple way for IceR and FAIMS data.

Best,

Mathias
