### ISSUE TITLE
Error - Less than two sample raw files are available

### ISSUE THREAD

**Issue by Maithy15** [mathiaskalxdorf/IceR#2]
I was trying to process some TOF  data acquired on Bruker Imact II Q-TOF using IceR. I am getting an error that less than two sample raw files are available. Please find the full log from R below.

[1] "2021-08-11 17:03:51 Job started"
[1] "2021-08-11 17:03:51 Preparation finished"
[1] "All files are already converted."
[1] "2021-08-11 17:03:51 Extraction finished"
Warning: Error in eval: Less than 2 sample raw files are available in the Raw files folder.

**Comment by mathiaskalxdorf** [comment]
Hey, 
can you check that in the raw files folder you have a new folder containing the converted data? Otherwise, IceR was only developed yet for data generated on Thermo Massspectrometers and Bruker timsTOF Pro. IceR will at the moment not know how to handle raw data from any other device.

**Comment by Maithy15** [comment]
Hi,
Thanks for the reply. I manually converted the data. I thought that TIMS-TOF measurement without the TIMS should look like the previous generation Bruker Q-TOF data. Maybe I am wrong.

**Comment by mathiaskalxdorf** [comment]
Hey,
as these devices will not report tims information, I assume that the data structure will look different and hence IceR will currently not know how to deal with this data. At the moment it can only work with Thermo data and data generated on a timsTOF Pro.

**Comment by Maithy15** [comment]
Thanks for the reply!
