### ISSUE TITLE
Processing IceR output question

### ISSUE THREAD

**Issue by k-p4** [mathiaskalxdorf/IceR#20]
Dear Mathias,

IceR is an exciting and useful tool! Could you please comment on processing output files? Do you have any recommendations? For instance, I was thinking of piping the output directly into MSStats, other in-house tools, or even Perseus so that non-proteomics persons can examine their data. Apologies if this has been addressed before; I may have missed it.

Thank You,
Karl

**Comment by mathiaskalxdorf** [comment]
Hi Karl, there are obviously multiple ways how to further process the data. We tried to describe here on the GitHub page with the example data set at least one initial further step. IceR comes with additional functions to further read-in the IceR results again into R, normalize and run differential expression analyses using Limma or PECA. I am not an expert for Perseus or MSStats but I assume both should be able to similarly read-in and further process the data. 

Best,

Mathias

**Comment by k-p4** [comment]
Thank you
