### ISSUE TITLE
GUI open but not responsive

### ISSUE THREAD

**Issue by DaliJarboui** [mathiaskalxdorf/IceR#22]
Dear IceR Developers, 
Was looking forward to try your tool, after following all your instructions, I was able to install everything without any error message, and open the IceR GUI interface, however, the buttons to choose directory, Maxquant folder, and results folder remain non-reponsive and not able to make any changes (there is no error message at all). 
Appreciate if you could help me to troubleshoot this issue to be able to run IceR
Thanks a lot

**Comment by mathiaskalxdorf** [comment]
Hey, can you provide more details? Which operating system do you use? Which version of R do you use? Which version of IceR (Master or Development-Branch) do you use?

**Comment by DaliJarboui** [comment]
I'm using the latest version of IceR (using the installation guideline provided in Github for windows 10, installed as well Rtools, ProteoWizard and RStudio), R version 4.1.3.
after running IceR, the GUI opens, but as I mentioned all the clicking buttons are unresponsive.
thanks for your help.

**Comment by DaliJarboui** [comment]
Dear IceR I managed to get IceR to start by trying to re-install it again, there was just the issue that once you try to locate the folder for files, it takes a bit longer to open the location of the files, on the other hand, I manged to run Maxquant results from the version 1.17.0. 
 the surprising part is that the data I tested were not LFQ data but iBAQ, and I got as results all the tables for features and proteins quantification, will check the data and update you if interested
