### ISSUE TITLE
Warning: Error in .rowNamesDF<-: invalid 'row.names' length   2: shiny::runApp   1: runIceR

### ISSUE THREAD

**Issue by Gourangasaha** [mathiaskalxdorf/IceR#3]
i am using IceR and having some problems in completion of my run.
_**Warning: Error in .rowNamesDF<-: invalid 'row.names' length
  2: shiny::runApp
  1: runIceR**_

**Comment by Gourangasaha** [comment]
Please help me with this issue.

**Comment by mathiaskalxdorf** [comment]
Hey, I would need more details. Can you please send the complete console output of the IceR run? Otherwise this error is too unspecific.

**Comment by mathiaskalxdorf** [comment]
Please give more details on the error. Especially the log in the R console can be very helpful.
