### ISSUE TITLE
 curiosity questions

### ISSUE THREAD

**Issue by giorgiolivi** [mathiaskalxdorf/IceR#9]
Dear All,

First thanks in advance for improvement of MaxQuant algorithm. 
I've tried your Shiny app and it works very well using orbitrap Raw files. 

I have just more a curiosity question.
If I would like switch my research and use timTOF Bruker  (including Ion Mobility separation) , is IceR compatible with Fragpipe 14.0 platform. 

In other words, fragpipe result folder is not well define as maxquant (full of TXT files) but contained plenty of subfolder in each of them there are a list of individually deconvolute files related to each run. 

Therefor is IceR also compatible with Fragpipe 14.0 platform?
Thanks in advance.
Regards,

**Comment by mathiaskalxdorf** [comment]
Hey, 

thanks for your interest in IceR. At the moment IceR does not support any other preprocessing pipeline than MaxQuant. However, we are working on the feature that data can be supplied in a very specific format which would allow, as long as data from other pipelines can be fitted into this format, usage of IceR for many other preprocessing pipelines. The feature should be out soon. A next step would be then to natively support outputs from other pipelines. 

Best regards.

**Comment by rugenni** [comment]
Dear Mathias, 

sorry if this is the wrong place for my question but I think it fits to the question of giorgiolivi: 

I am also very interested in using IceR for our upcoming projects running on the the timsTOF platform. Our current problem is, that we cannot get MaxQuant 1.5.X/1.6.X running on our new systems and so we have to use MQ 2.X.X.X. (I assume I tried nearly everything to this point). 

Will this update you talked about also make it possible to work with the output of these newer versions of MaxQuant? 

I already tried MQ 2.0.1.0 with IceR and I think that the Cox people rearranged the MQ output in a way that makes them incompatible with IceR (like for example there is no longer a "resolution" column in the evidence.txt.)

Could you give any comment on that? 

Cheers,
Nils

**Comment by mathiaskalxdorf** [comment]
Hi Nils,

many thanks for this question. The resolution column is actually not mandatory. So if this is the only change it should work fine. Nonetheless, I will have a look on some example data how the new MaxQ output with Version 2+ looks like and would adjust (if necessary) IceR accordingly. Still, with the new version of IceR (hopefully soon) you would still also be able to simply manually prepare data into the required minimal format which would allow usage of IceR even if MaxQ is changing formats again (in the future).

I keep you updated.

Best,

Mathias

**Comment by mathiaskalxdorf** [comment]
Hey,

just a note. I pushed a new version of IceR to Github (development branch, V1.2.0). It now allows usage of preprocessed data by any pipeline as long as the data is supplied in a specific format. Please have a look in the description for more details. Furthermore, I tested IceR for data preprocessed by MaxQuant V2.0.3.0 and it works fine.

Best,

Mathias

**Comment by rugenni** [comment]
Thanks a lot Mathias. 

Just a short question to be clear: Did you test version 0.9.9. for the compatability with MQ 2.0.3.0 or will I need to use IceR 1.2.0? 

Again many thanks,
Nils

**Comment by mathiaskalxdorf** [comment]
I suggest using the development version V1.2.0 as I tested it for MaxQ V2.0. Nonetheless, it should work as well with the master version 0.9.10 but I did not explicitly test it there.
Best

**Comment by giorgiolivi** [comment]
Dear Mathias,
Thanks a lot,
I will try it  ASAP.
Best.
